name: 'Init'
description: 'Init environment variables'


inputs:
  env-json:
    description: 'base64 json'
    required: true



runs:
  using: "composite"
  steps: 
    - run: |
        echo ${{ inputs.env-json }} | base64 --decode > data.json
        CONTAINERREGISTRY=$(jq '.REGISTRY' data.json)
        REGISTRY_SUBPATH=$(jq '.REGISTRY_SUBPATH' data.json)
        COMPANY=$(jq '.COMPANY' data.json)
        KUBEBOT=$(jq '.KUBEBOT' data.json)
      shell: bash

