name: 'test4'
author: 'Kevin Li'
description: 'test lib'

inputs:
  v1:
    description: 'test v1'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps: 
    - run: |
        echo "12345"
        echo ${{ inputs.who-to-greet }}
      shell: bash
    - run: $GITHUB_ACTION_PATH/script.sh 
      shell: pwsh