name: 'Docker Build'
description: 'build image, push image (optional)'


inputs:
  env-json:
    description: 'docker registry'
    required: true



runs:
  using: "composite"
  steps: 
    - run: |
        echo ${{ inputs.env-json }}

 #       echo ${{ inputs.env-json }} > data.json
 #       CONTAINERREGISTRY=$(jq '.REGISTRY' data.json)
 #       REGISTRY-SUBPATH=$(jq '.REGISTRY-SUBPATH' data.json)
#        COMPANY=$(jq '.COMPANY' data.json)
 #       KUBEBOT=$(jq '.KUBEBOT' data.json)
      shell: bash

