name: 'test45'
author: 'Kevin Li'
description: 'test lib'

inputs:
  registry:
    description: 'docker registry'
    required: true
    default: 'containerregistrydev.azurecr.io'
  registry-subpath:
    description: 'registry subpath'
    required: true
    default: 'webjet'  
  image-name:
    description: 'docker image name'
    required: true
    default: 'webjet-github'
  build-args:
    description: 'docker build args'
    required: true
    default: '-'
  dockerfile-path:
    description: 'dockerfile path'
    required: true
    default: '-'
  push:
    description: 'also push image'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps: 
    - run: |
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $GITHUBSHA | cut -c1-6)
        $INPUT_REGISTRY=${{ inputs.registry }}
        $INPUT_BUILDARGS=${{ inputs.build-args }}
        $INPUT_IMAGENAME=${{ inputs.image-name }}
        $INPUT_TAG=$TAG
        $INPUT_DOCKERFILED_PATH=${{ inputs.dockerfile-path }} 
        $INPUT_FLAG_PUSH=${{ inputs.push }}
        chmod +x $GITHUB_ACTION_PATH/test.sh
        $GITHUB_ACTION_PATH/test.sh
      shell: bash
    # - run: |
    #     chmod +x $GITHUB_ACTION_PATH/test.sh
    #     $GITHUB_ACTION_PATH/test.sh ${{ inputs.registry }} ${{ inputs.build-args }} ${{ inputs.image-name }} $TAG  ${{ inputs.dockerfile-path }} ${{ inputs.push }}
    #   shell: bash
