name: 'test'
author: 'Kevin Li'
description: 'test lib'

inputs:
  v1:
    description: 'test v1'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps: 
      run: echo ${{ inputs.v1 }}
      shell: bash
