name: 'test2'
author: 'Kevin Li'
description: 'test lib'

inputs:
  v1:
    description: 'test v1'
    required: true
    default: 'dev'

runs:
  using: "composite"
  steps: 
    - run: |
        echo "1234"
        echo ${{ inputs.who-to-greet }}

      shell: bash
