name: 'test45'
author: 'Kevin Li'
description: 'test lib'

inputs:
  registry:
    description: 'docker registry'
    required: true
    default: 'containerregistrydev.azurecr.io'
  registry-subpath:
    description: 'registry subpath'
    required: true
    default: 'webjet'  
  image-name:
    description: 'docker image name'
    required: true
    default: 'webjet-github'
  build-args:
    description: 'docker build args'
    required: false
  dockerfile-path:
    description: 'dockerfile path'
    required: false

runs:
  using: "composite"
  steps: 
    - run: |
        echo "12345678"
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $GITHUBSHA | cut -c1-6)
        chmod +x $GITHUB_ACTION_PATH/test.sh
        $GITHUB_ACTION_PATH/test.sh ${{ inputs.registry }} ${{ inputs.build-args }} ${{ inputs.image-name }} $TAG  ${{ inputs.dockerfile-path }}
      shell: bash
