name: 'Init'
description: 'Init environment variables'


inputs:
  env-json:
    description: 'base64 json'
    required: true



runs:
  using: "composite"
  steps: 
    - run: |
        echo ${{ inputs.env-json }} | base64 --decode > data.json
        export CONTAINERREGISTRY=$(jq '.REGISTRY' data.json)
        export COMPANY=$(jq '.COMPANY' data.json)
        export KUBEBOT=$(jq '.KUBEBOT' data.json)
        echo $CONTAINERREGISTRY
        echo $COMPANY
        echo $KUBEBOT
      shell: bash

