name: 'test45'
author: 'Kevin Li'
description: 'test lib'

inputs:
  registry:
    description: 'docker registry'
    required: true
    default: 'containerregistrydev.azurecr.io'
  image-name:
    description: 'docker image name'
    required: true
    default: 'webjet-github'

runs:
  using: "composite"
  steps: 
    - run: |
        echo "1234567"
        GITHUBSHA=${{ github.sha }}
        TAG=$(echo $TAG | cut -c1-6)
        echo $TAG
        chmod +x $GITHUB_ACTION_PATH/test.sh
        $GITHUB_ACTION_PATH/test.sh ${{ inputs.registry }} ${{ inputs.image-name }}
      shell: bash
