name: 'Init'
description: 'Init environment variables'


inputs:
  env-json:
    description: 'base64 json'
    required: true



runs:
  using: "composite"
  steps: 
    - run: |
        echo ${{ inputs.env-json }} | base64 --decode > data.json
        CONTAINERREGISTRY=$(jq '.REGISTRY' data.json)
        COMPANY=$(jq '.COMPANY' data.json)
        KUBEBOT=$(jq '.KUBEBOT' data.json)
        echo "::set-env name=CONTAINERREGISTRY::$CONTAINERREGISTRY"
        echo "::set-env name=COMPANY::$COMPANY"
        echo "::set-env name=KUBEBOT::$KUBEBOT"
        echo $CONTAINERREGISTRY
        echo $COMPANY
        echo $KUBEBOT
      shell: bash

