name: 'Docker Build'
description: 'build image, push image (optional)'

inputs:
  company:
    description: 'Company'
    required: true
    default: 'Kevin-Li-Webjet'
  repo:
    description: 'repo'
    required: true
    default: 'Git-Action-Test'  
  release-id:
    description: 'release id'
    required: true
  file-name:
    description: 'log file name'
    required: true
    default: 'logs.zip'

runs:
  using: "composite"
  steps: 
    - run: |
        export INPUT_FILENAME=${{ inputs.file-name }}

        export INPUT_COMPANY=${{ inputs.company }}
        export INPUT_REPO=${{ inputs.repo }}
        chmod +x $GITHUB_ACTION_PATH/download.sh
        $GITHUB_ACTION_PATH/download.sh

        export INPUT_RELEASE_ID=${{ inputs.release-id }}
        chmod +x $GITHUB_ACTION_PATH/upload.sh
        $GITHUB_ACTION_PATH/upload.sh
      shell: bash

